// Public evidence imports are deliberately excluded from the reviewed matching bank.
import {readFileSync,readdirSync,statSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import initRDKit from '@rdkit/rdkit';
import converter from 'jcampconverter';
import {openBank,stats} from '../lib/bank.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),dir=path.join(root,'data'),downloads=path.join(dir,'source-downloads'),extracted=path.join(downloads,'extracted');
const db=openBank(dir,path.join(root,'catalog','identities.json')),rdkit=await initRDKit();
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const identityCache=new Map(),identities=new Map(db.prepare('SELECT * FROM compounds').all().map(c=>[c.inchikey,c]));
function identity(smiles,key,name){let computed=null; if(smiles){if(identityCache.has(smiles))computed=identityCache.get(smiles);else{let mol;try{mol=rdkit.get_mol(smiles);if(mol)computed=rdkit.get_inchikey_for_inchi(mol.get_inchi());}catch{}finally{mol?.delete()}identityCache.set(smiles,computed);}}const mismatch=!!(key&&computed&&key!==computed),inchikey=key||computed||null,c=inchikey&&!mismatch?identities.get(inchikey):null;return {inchikey,smiles:smiles||null,compoundId:c?.id||null,name:c?.name||name||inchikey||'Unnamed source structure',identityMismatch:mismatch};}
// RFC 4180 quoting (commas, escaped quotes and embedded newlines) without number coercion.
function csv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Unclosed CSV quote');if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows;}
function addSource(id,title,url,license,archives,notes){const metadata={notes,archives:archives.map(f=>JSON.parse(readFileSync(path.join(downloads,f+'.provenance.json'),'utf8')))};db.prepare('INSERT OR IGNORE INTO external_sources VALUES(?,?,?,?,?)').run(id,title,url,license,JSON.stringify(metadata));}
const insert=db.prepare('INSERT INTO external_evidence VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET metadata=excluded.metadata,data=excluded.data,status=excluded.status');
const failures=[],fileHashes=new Map();let added=0;
function put({source,record,identity:i,technique,representation,url,original,filename,metadata={},parsed=null,data=null,quarantine=false}){const id=hash(source+'|'+record+'|'+technique+'|'+representation).slice(0,32);if(!fileHashes.has(original))fileHashes.set(original,hash(readFileSync(original)));const relative=path.relative(dir,original);if(relative.startsWith('..')||path.isAbsolute(relative))throw Error('Original path outside bank');const result=insert.run(id,source,record,i.compoundId,i.name,i.inchikey,i.smiles,technique,representation,quarantine||i.identityMismatch?'quarantined':'imported',url,relative,filename||path.basename(original),fileHashes.get(original),JSON.stringify({...metadata,identityMismatch:i.identityMismatch||false,review:'Imported; not independently reviewed; excluded from matching'}),parsed?JSON.stringify(parsed):null,data?JSON.stringify(data):null);added+=Number(result.changes);}
function points(x,y){if(!x||!y||x.length!==y.length||x.length<3)throw Error('Missing or unequal numerical arrays');const p=x.map((v,i)=>[Number(v),Number(y[i])]);if(p.some(v=>v.some(n=>!Number.isFinite(n))))throw Error('Non-finite value');p.sort((a,b)=>a[0]-b[0]);if(p.some((v,i)=>i&&v[0]===p[i-1][0]))throw Error('Duplicate x values');return {points:p,range:[p[0][0],p.at(-1)[0]]};}
function transaction(fn){db.exec('BEGIN IMMEDIATE');try{fn();db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
addSource('chemotion-ir','Chemotion experimental IR collection','https://doi.org/10.22000/OGoEQGlsZGElrgst','CC BY-SA 4.0',['chemotion-ir.tar'],'JCAMP-DX original/processed traces and separately identified automatic peak tables; acquisition conditions vary. Dataset attribution retained per record.');
transaction(()=>{
 const metaPath=path.join(extracted,'chemotion-ir','10.22000-OGoEQGlsZGElrgst','data','dataset','meta_data.json');const entries=JSON.parse(readFileSync(metaPath,'utf8'));const files=new Map(readdirSync(path.join(extracted,'chemotion-jdx'),{recursive:true}).filter(f=>statSync(path.join(extracted,'chemotion-jdx',f)).isFile()).map(f=>[path.basename(f),path.join(extracted,'chemotion-jdx',f)]));
 for(const e of entries)for(const dataset of e.datasets||[])for(const a of dataset.attacments||[]){const original=files.get(path.basename(a.identifier));if(!original){failures.push({source:'chemotion-ir',id:a.identifier,error:'File missing'});continue;}const raw=readFileSync(original,'utf8'),i=identity(e.cano_smiles,null,'Chemotion sample '+e.sample_id);const metadata={sampleId:e.sample_id,analysisId:e.analysis_id,instrument:dataset.instrument,authors:e.authors,affiliations:e.affiliations,reportedDescription:e.content,metadataOriginal:path.relative(dir,metaPath),xUnit:'cm-1',processing:'JCAMP converted with MIT jcampconverter 9.0.0; original units retained; no intensity rescaling'};
 try{const converted=converter.convert(raw,{keepRecordsRegExp:/.*/});const blocks=(converted.flatten||[]).flatMap(block=>(block.spectra||[]).map(s=>({block,s})));const full=blocks.find(({s})=>s.isXYdata&&s.data?.x?.length>=3);const peak=blocks.find(({s})=>!s.isXYdata&&s.data?.x?.length);const chosen=full||peak;if(!chosen)throw Error('No supported XY data block');const {s,block}=chosen;if(!/^1\/CM$|^CM-1$|^CM\^-1$/i.test(s.xUnits||''))throw Error('Unsupported x units '+s.xUnits);const parsed=points(s.data.x,s.data.y);if(s.nbPoints&&s.nbPoints!==parsed.points.length)throw Error('NPOINTS does not match decoded points');if(full&&(Math.abs(parsed.range[0]-Math.min(s.firstX,s.lastX))>0.05||Math.abs(parsed.range[1]-Math.max(s.firstX,s.lastX))>0.05))throw Error('Decoded range disagrees with header');put({source:'chemotion-ir',record:a.identifier,identity:i,technique:'ftir',representation:full?'continuous':'peak-table',url:'https://doi.org/10.22000/OGoEQGlsZGElrgst',original,filename:a.filename,metadata:{...metadata,yMode:s.yUnits,format:full?'continuous':'peaks',title:block.title,header:block.info,converterLogs:converted.logs},parsed});}
 catch(error){failures.push({source:'chemotion-ir',id:a.identifier,error:error.message});put({source:'chemotion-ir',record:a.identifier,identity:i,technique:'ftir',representation:'unparsed-jcamp',url:'https://doi.org/10.22000/OGoEQGlsZGElrgst',original,filename:a.filename,metadata:{...metadata,parseError:error.message},quarantine:true});}
 }
});console.log('Chemotion imported');
addSource('uv-advisor','UV-adVISor published experimental UV datasets I and II','https://doi.org/10.1021/acs.analchem.1c03741','CC BY 4.0 (Figshare deposit)',['uv-advisor-supplement.zip'],'Experimental spectra after source baseline correction and maximum normalization. Not instrument raw data. Predicted/scrambled spectra excluded.');
transaction(()=>{for(const dataset of ['I','II']){const original=path.join(extracted,'uv-advisor','Datasets I, II, III spectra and SMILES','Dataset_'+dataset+'.csv');const [header,...rows]=csv(readFileSync(original,'utf8'));for(let n=0;n<rows.length;n++){const row=rows[n],x=header.slice(2).map((s,j)=>dataset==='I'?220+j:Number(s)),y=row.slice(2);const parsed=points(x,y);if(parsed.points.length!==(dataset==='I'?181:171))throw Error('Unexpected UV columns');const i=identity(row[1],null,row[0]);put({source:'uv-advisor',record:dataset+':'+n,identity:i,technique:'uv',representation:'continuous-normalized',url:'https://doi.org/10.1021/acs.analchem.1c03741',original,metadata:{dataset,sourceName:row[0],rowIndex:n,xUnit:'nm',yMode:'relative absorbance (source-normalized 0–1)',format:'continuous',processing:'Source baseline-offset and maximum-normalized; not raw absorbance',instrument:dataset==='I'?'Thermo Dionex Ultimate U3000 / DAD-3000RS':'SpectraMax iD5 microplate spectrophotometer',solvent:dataset==='I'?'Water/acetonitrile + 0.1% formic acid gradient; elution composition varies':'Water with 2% DMSO',conditionsNote:dataset==='I'?'Do not equate HPLC elution solvent with stock-solution solvent.':'Paper has a concentration unit inconsistency (10 mM stock / 50-fold dilution vs printed 200 mM); verify original experimental protocol before comparison.'},parsed});}}});console.log('Experimental UV I/II imported; model predictions and dataset III omitted');
addSource('npmrd','NP-MRD experimental NMR assignments and unassigned peak positions','https://np-mrd.org/downloads','CC BY-NC 4.0',['npmrd-assignments.zip','npmrd-peaks.zip','npmrd-metadata-00001-50000.zip'],'Numerical experimental chemical shifts only, not FIDs or full intensity traces. Noncommercial terms. Metadata coverage NP0000001–NP0050000; unmatched accessions retained without guessed identities.');
const npProducts=JSON.parse(readFileSync(path.join(extracted,'npmrd-metadata','npmrd_natural_products_NP0000001_NP0050000.json'),'utf8')).np_mrd.natural_product;const npMap=new Map(npProducts.map(e=>[e.accession,e]));
transaction(()=>{for(const [folder,representation]of [['npmrd-assignments','assigned-shifts'],['npmrd-peaks','peak-positions']])for(const filename of readdirSync(path.join(extracted,folder))){const accession=filename.match(/NP\d{7}/)?.[0];if(!accession)continue;const e=npMap.get(accession),i=identity(e?.smiles,e?.inchikey,e?.name||accession),original=path.join(extracted,folder,filename),rows=csv(readFileSync(original,'utf8'));for(const [nucleus,technique]of [['H','h1'],['C','c13']]){const selected=rows.filter(r=>r[0]===nucleus&&r[representation==='assigned-shifts'?2:1]?.trim()).map(r=>{const text=r[representation==='assigned-shifts'?2:1];return {shift:Number.isFinite(Number(text))?Number(text):null,shiftText:text,...(representation==='assigned-shifts'?{atom:r[1],multiplicity:r[3]||null,couplingText:r[4]||null}:{})}});if(!selected.length)continue;const invalid=selected.some(p=>p.shift===null&&!/^(NA|N\/A|ND|Not Determined)$/i.test(p.shiftText));put({source:'npmrd',record:filename,identity:i,technique,representation,url:'https://np-mrd.org/natural_products/'+accession,original,metadata:{accession,xUnit:'ppm',intensity:'Not supplied; no artificial intensities generated',missingShifts:selected.filter(p=>p.shift===null).length,identityMetadataAvailable:!!e,acquisition:'Solvent, frequency and temperature must be checked in the original record'},data:selected,quarantine:invalid});}}});console.log('NP-MRD shifts imported');
addSource('irexp','IRexp literature-mined structure-linked IR band lists','https://huggingface.co/datasets/ilkhamfy/IRexp','CC BY 4.0 packaging; per-record source licenses retained',['irexp-resolved-commercial.jsonl.gz','irexp-NOTICE.txt','irexp-license-remediation.md'],'Literature-extracted bands and verbatim NMR text, not full spectral traces. Manuscript in preparation, not a validated curated reference. Shared/suspect band lists quarantined.');
transaction(()=>{const original=path.join(downloads,'irexp-resolved-commercial.jsonl.gz');const lines=gunzipSync(readFileSync(original)).toString('utf8').split('\n');let n=0;for(const line of lines){if(!line.trim())continue;const e=JSON.parse(line),i=identity(e.smiles,e.inchikey,'Literature structure '+e.inchikey),url=e.pmcid?'https://pmc.ncbi.nlm.nih.gov/articles/'+e.pmcid+'/':e.source_doi&&!e.source_doi.startsWith('PMC:')?'https://doi.org/'+e.source_doi:'https://huggingface.co/datasets/ilkhamfy/IRexp';const metadata={recordId:e.id,lineIndex:n++,sourceDoi:e.source_doi,pmcid:e.pmcid,license:e.license,licenseRaw:e.license_raw,sharedInPaper:e.ir_shared_in_paper,tableFlattenSuspect:e.ir_table_flatten_suspect,refetchConfirmed:e.ir_refetch_confirmed,extraction:'Automated literature mining; verify compound-to-band assignment in original article'};const quarantine=!!(e.ir_shared_in_paper||e.ir_table_flatten_suspect);if(e['ir_bands_cm-1']?.length)put({source:'irexp',record:e.id+':'+metadata.lineIndex,identity:i,technique:'ftir',representation:'reported-bands',url,original,metadata,data:e['ir_bands_cm-1'],quarantine});for(const [key,technique]of [['h_nmr','h1'],['c_nmr','c13']])if(e[key]?.trim())put({source:'irexp',record:e.id+':'+metadata.lineIndex,identity:i,technique,representation:'reported-text',url,original,metadata,data:e[key],quarantine});}});console.log('IRexp bands / NMR text imported');
// Exact duplicate numerical curves are flagged, not counted as new experiments.
transaction(()=>{const seen=new Map(),update=db.prepare('UPDATE external_evidence SET metadata=? WHERE id=?');for(const e of db.prepare("SELECT id,source_id,inchikey,metadata,parsed FROM external_evidence WHERE representation LIKE 'continuous%' ORDER BY source_id,filename LIKE '%.peak.jdx',id").iterate()){const m=JSON.parse(e.metadata),traceHash=hash(e.source_id+'|'+e.inchikey+'|'+m.yMode+'|'+e.parsed),duplicateOf=seen.get(traceHash)||null;if(!duplicateOf)seen.set(traceHash,e.id);update.run(JSON.stringify({...m,traceHash,duplicateOf}),e.id);}});
const report={completedAt:new Date().toISOString(),processedRows:added,failures,external:stats(db).external,policy:'No imported row is approved for matching. Curves, assigned shifts, unassigned positions and literature text are separate representations. Exact numerical duplicate curves are flagged. No synthetic spectra were generated.'};
writeFileSync(path.join(root,'spectra-import-report.json'),JSON.stringify(report,null,2));db.exec('PRAGMA optimize');db.close();console.log(JSON.stringify({processedRows:added,failures:failures.length,total:report.external.total,linkedCatalogIdentities:report.external.linkedIdentities,uniqueCurves:report.external.uniqueCurves,groups:report.external.groups},null,2));
